dist: trusty
language: go
go:
  - 1.12.x
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS gokitstest DEFAULT CHARSET utf8mb3 COLLATE utf8_general_ci;'
  - export MYSQL_DATA_SOURCE_NAME="travis:@/gokitstest?parseTime=true&multiStatements=true&charset=utf8"
  - export GO111MODULE=on
addons:
  sonarcloud:
    organization: "charlemaznable"
script:
  - go test -test.bench=.* -coverprofile=coverage.txt -covermode=atomic
  - sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)
