language: go
go:
  - 1.12.x
install: go get github.com/CharLemAznable/gokits
script: go test -test.bench=.* -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
